### ISSUE TITLE
Cloudformation template times out

### ISSUE THREAD

**Issue by dsielert** [rhythmictech/terraform-aws-ecs-cluster#5]
Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 80% MinSuccessfulInstancesPercent requirement

**Comment by smiller171** [comment]
@dsielert Sorry I'm just seeing this.

Could you give more details? This is working well for us but I'd like to understand what you're doing differently that's causing it to fail (though you've likely moved on by now)

**Comment by dsielert** [comment]
I moved on .. it wasn't receiving the cfm signals ..

**Comment by smiller171** [comment]
Ah. That bit requires your AMI be set up to send them. I should add that to the readme, and maybe an option in the TF to disable it. Thanks @dsielert
